### ISSUE TITLE
Change behaviour by cuckoo monitor

### ISSUE THREAD

**Issue by 3ntr0phy** [cuckoosandbox/monitor#82]
Hello,
I am trying to understand how and if it is possible to actually hook a function with the monitor and change runtime the arguments of it.
I am trying to change the code over hook.c and inject.c but doesn't seem really effective.
Thank you

**Comment by baxitaurus** [comment]
The hooks are defined in the `*.rst` files under the `sigs` folder, the correct syntax for doing so is documented here https://cuckoo-monitor.readthedocs.io/en/latest/hooks.html.

If you want to change the arguments of a call at runtime you should place the proper code under a `Pre::` block.

You should never edit the `hook.c` directly because it's produced during the `make` from the content of those `rst` and some Jinja templates.

**Comment by 3ntr0phy** [comment]
Ok Thank you!
But I notice that the code in `Pre::` is not put at the beginning of the function actually, for example in `NtCreateFile` it is put after `if(hook_in_monitor() != 0) ` .

**Comment by baxitaurus** [comment]
Yeah that's correct, there's always some code that is added in addition to the one produced based on the `*.rst` signatures. You shouldn't care about it unless you won't to hack some base behavior of the monitor.

**Comment by 3ntr0phy** [comment]
Okay thank you very much.
